---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-test
    spec:
      containers:
      - image: debian:jessie
        name: deployment-test
        command: ['sh', '-c', 'while true; do echo "Hello, ${USERNAME}!"; sleep 10; done']
        env:
         - name: USERNAME
           value: $(USERNAME)

